### ISSUE TITLE
Resleeving Infomorph

### ISSUE THREAD

**Issue by itteerde** [itteerde/ep2eRules#1]
As Infomorph, if not changing the kind of Infomorph, after Egocasting, do you have to do any of the Resleeving Tests: Integration Test (288) or Resleeving Stress Test (289) as you neither get a new Morph, nor have anything to adapt/catch up?

- https://discord.com/channels/575153209065340929/1082012122050990192/1228190060072013865

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/ep2eRules/assets/8367477/3d512cbf-3645-489c-8c37-2d514550aa24)

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/ep2eRules/assets/8367477/2e59bfb0-5e92-41b3-9a8a-cd10f41bbbdd)

**Comment by itteerde** [comment]
So I think unless changing the type (`Morph`) of `Infomorph` (like `Agent` to `Operator`) there is no resleeving unless one is restored or booted up after some significant time has passed. Assuming the intention is indeed for this to not happen for `Egocasting` the new lower bounds for that would be in the hours. So moving not a problem at all. Doing something there however (bots) is, and indeed without `Drone Affinity` means `Integration Test`.

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/ep2eRules/assets/8367477/3e5d05a0-4945-4a8f-bd38-9c60de9de933)

**Comment by itteerde** [comment]
**Resleeving** (pg. 288)
> Resleeving — also called downloading or remorphing — is the process where your ego takes on a new physical body. You may be switching because you want a new morph or because you are egocasting to a new destination; this transfer is usually a smooth transition from one sleeve to the next while conscious.

So I think now that the whole `Resleeving` should never be used for `Informorph`. I do think it should all/only `Willpower Stress Test` (pg. 229), usually for `Continuity` reasons.

**Comment by PhDaveMil** [comment]
The book clearly says no. That means no. When egocasting, you are essentially slowly transfering yourself from A to B, keeping yourself running across both systems, and only deleting parts of yourself once they are fully instantiated on a new system. Egocasting might take a lot of time due to distance based lag, but in terms of physical process it is no different than moving yourself from one device to another. That never causes any form of resleeving test or continuity loss for infomorphs. This, of course, assumes that you have actually egocasting, not sending a backup of yourself to a new location and having it spun up there. The two are two completely different processes.

**Comment by itteerde** [comment]
also copying does not lose continuity
> As a digital being, you may also copy yourself. This takes a full action turn and creates an alpha fork ▶292. Copied infomorphs do not lose continuity. If you are copied to a different type of infomorph, this counts as resleeving ▶288. Your copy includes your digital code ▶299 along with a cryptographically signed incremental number indicating which copy it is.
Infomorphs acquired from commercal code studios (i.e., most agents, ikons, and operators) have built-in digital restrictions that prevent you from running more than one copy of that morph at a time. Instead, the copy instantiates in a standard digimorph. This copy restriction may be cracked in the same manner as digital blueprints (Cracking Blueprints ▶314). Code houses offer bounties for reports of people using cracked infomorph code. In many jurisdictions, copying oneself is frowned upon or flat-out illegal. Some polities require infomorphs to be encoded with copylock and auto-erase meshware ▶326 to prevent unauthorized copying and delete the fork upon reaching a legally mandated time limit.
