### ISSUE TITLE
Taking Damage, Unconsciousness, Reboot, ...

### ISSUE THREAD

**Issue by itteerde** [itteerde/ep2eRules#10]
Taking Damage, Unconsciousness, Reboot, ...

**Comment by itteerde** [comment]
For some of it I assume considering `Computerized Device` (pg. 250) will be the important category and distinction (though much will remain complex with one system often have several parts being such `Devices`, possibly even before having `Slaved Devices`).

**Comment by PhDaveMil** [comment]
Note for future adjudication: only morphs are subject to knockdown and unconsciousness; shells instead suffer the crash rules found at the end of the same sections where the rules for knockdown and unconsciousness are explained.
