### ISSUE TITLE
Anonymizer able to proxy chain?

### ISSUE THREAD

**Issue by itteerde** [itteerde/ep2eRules#2]
Does everyone need an Anonymizer (pg. 315) subscription to use it, or can a crew buy one and route the crews hacking/communications meant to be anonymous through that crew member's Mesh Inserts (at least if in VPN with them)? 

- https://discord.com/channels/575153209065340929/1082012122050990192/1228678541177258045

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/ep2eRules/assets/8367477/d2b690a8-245c-4c7b-952c-a1f4cdc1d94e)

**Comment by itteerde** [comment]
Can we agree with Happy Fox:
> you let muiltiple people use it, but they take penalties like on an overloaded mesh network (which is basically what it is)
@PhDaveMil ?

**Comment by PhDaveMil** [comment]
We talked, and it seems it is not a good idea to agree with Happy Fox. As you understand the IT reason better than I do, Erik, I will let you explain it.

**Comment by itteerde** [comment]
Actually, now having talked about it, the traffic would be all the subscriber, so it would require doing VPN on-top, so not by itself, so no. Otherwise the endpoint would be the subscriber for all traffic down from the service never reaching the sharing parties.
