### ISSUE TITLE
Rebooting Infomorph: Resleeving Tests?

### ISSUE THREAD

**Issue by itteerde** [itteerde/ep2eRules#3]
Does `Rebooting` (pg. **261**, 264) cause any `Resleeving Tests` (pg. 288) for `Infomorphs`?

**Comment by itteerde** [comment]
It might or might not apply to `Cyberbrain`. I think the outcome will be no anyways, so that can be discussed if it should turn out to end with either or both of the `Resleeving Tests` to be applied.

**Comment by PhDaveMil** [comment]
Maybe? My original answer was yes. I am not so sure after gathering quotes. An infomorph is considered to be "alive" only so long as it is actively run on a device. As soon as no device in existence is running the infomorph, the infomorph is considered to be "dead." There is, however, a line of text that makes it questionable whether a reboot counts as death or not. This follows from the following: 

"Whereas a backup is just an inactive file, infomorphs are software executables, active programs that bring the ego to electronic life." (Page 252)

"Every infomorph **_must_** be run on a specific host or server — your home device. . . . Your home device stores your mind-state files and handles the processing needs of your mind-emulation suite." (252, emphasis added) 

"The safety of your home device is important. If it is shut down, you shut down with it, rebooting along with the device later. If the device is destroyed, you are killed, though your data may be recoverable from salvaged components . . ." (252)

That last seems to suggest a difference between rebooting and death. Given that last line, I think that rebooting certainly should not induce a SOM check. It does, however, still create a continuity breech. Given the tables on page 229, I think that should call for a WILL check or 1d6 Stress damage from the Alienation category.

**Comment by itteerde** [comment]
`Resleeving Stress Test` (pg. 289):
> The Resleeving Stress Test incorporates all of the mentally challenging aspects of downloading into a new body into a single test: alienation, continuity, remembering death, and lack.

- As it is not a new body, reading *new* as different in this case, think it is quite obvious that this is not about a body being old or young, I think it does not apply.
- I also have a weaker case in that it is not a body at all for `Infomorph`. But I do conceed that the `Infomorph` is a game concept trying to keep `Infomorph` somewhat in line with others, therefore they could be meant despite being talked about *body*. Yet, this *body* then should be the kind of `Infomorph`, so `Agent` vs. `Operator`..., not about the `Home Device`.
- I do conceed that the paragraph is mixing up different stuff though, therefore my case not being a slam dunk decided with this argument.

**Comment by itteerde** [comment]
Do you think that going unconcious (even for 3s) will require some `Resleeving Tests` for a `Biomorph`? If not I think we can come to a solid no to the whole issue question, right?

**Comment by PhDaveMil** [comment]
The difference is that an unconscious body is still biologically alive--or on--in the way that a rebooted device isn't, at least momentarily. I think that if someone suffered brain death for 3-18 seconds and then had some tech bring them back from the brink--rebooting their brain--then they would also suffer continuity loss and need to roll a WILL check or suffer 1d6 stress.

**Comment by itteerde** [comment]
> Given the tables on page 229, I think that should call for a WILL check or 1d6 Stress damage from the Alienation category.

- That is 1d6 for less than three months though. I think even the max. 18s would then be way more along the 0 then the 1d6 lines.
- Yet, I would not fight 1d6 (think more like 1d6-1 as I still think such a hickup is even less severe than any of the 1d6-1 stressors) on `Willpower Stress Test` (pg. 229). While I do think that it is wrong it does not really matter (especially if 1d6-1) unless an `Infomorph` or `Synth` is also a face.

**Comment by itteerde** [comment]
`Continuity` (pg. 107):
> Most people back up often to minimize the risk of lack and regularly record an experience playback (XP) lifelog of their own daily lives so they can “catch themselves up” if an unexpected death occurs.

I do not conceed that this 🔴**risk** is only about the difference between 1d6 and 1d10, but I do conceed that it is a possible reading.

**Comment by PhDaveMil** [comment]
Final ruling: Rebooting does not require any form of resleeving test. Given that it does logically create a disruption of continuity however, at my discretion, I reserve the right to call for an Alienation stress test (WILL or 1d6-1 Stress damage).
