### ISSUE TITLE
What Gear is needed to add flight on Iapetus to Bots?

### ISSUE THREAD

**Issue by irmejnah** [itteerde/ep2eRules#5]
What Gear is needed to add flight on Iapetus to Bots?
- `Personal Transport` (pg. 353) has `Rocket Pack`, `Sled` and `Thruster Pack`. The `Sled` seems to be a real, though minimalistic, vehicle. For Bots the `Thruster Pack` would be expected by name and even by the description text, except that it explicitly says `micrograv`, where `Rocket Pack` explicitly says how one can fly with it in all gravity. So is it `Rocket Pack` for the `GP` balancing (as it gives that function range), just understood to be integrated thrusters in the bot case, or is it `Thruster Pack` because it is thruster packs (there could be a case that thrusters on a bot need less stuff to make it suitable for fragile stuff such as humans, but then `Rocket Pack` if used by `Biomorph` still needs protective gear, so probably `Rocket Pack` for bots, too?

**Comment by irmejnah** [comment]
Also, the seemingly *fairer* way having it be `Rocket Pack` for all would simplify loadout if `Nanofabbing` and I guess if bringing pieces being free to integrate with either `Biomorph` or `Robot`.

**Comment by PhDaveMil** [comment]
The Thruster Pack says that it uses Thrust Vector (Rocket) on page 353, but on page 353 it provides the following description: "Worn for micrograv operations or EVA in vacuum, this thruster pack uses vectored thrust nozzles to maneuver." This is a description of real world, modern gas jets used by astronauts. Given that the Rocket Pack has a higher GP cost, it seems like the Rocket Pack is supposed to be used in all environments and the Thruster Pack in micrograv only (which would explain its lower GP cost). That would suggest that version 1.3 needs some erata, and based on the movement rules in 1.3, the Thruster Pack is supposed to be labeled as a gas jet vehicle, not a rocket vehicle. We will treat it as such in our campaigns.

**Comment by itteerde** [comment]
- `Mobility System Thrust Vector (Rocket)`
