### ISSUE TITLE
Gear Sizes

### ISSUE THREAD

**Issue by irmejnah** [itteerde/ep2eRules#6]
As many gear sizes are not given, it is a bit of a problem in planning. Size does not only matter for transport, but also for `Nanofabbing`, though there some items might have another size for `Nanofabbing` than the item in use has. Some might also have a different one for transport if not deployed.
- `Emergency Bubble` is *large but portable*, and if not deployed a `package`. So does it really deploy much larger than `Large`, or has a very bad packaging ratio (hard to believe as its utility is precisely being empty space to be used by the 4+ people (comfortable, so cramping should allow for more)). I'd suggest it should be `Small` for transport and printing (a backpack), and deploy `Very Large`, interpreting the *large* in the text as an unfortunate choice of words. As the `Pressure Tent` is technically (though I'd expect being more cramped) providing the same space, otherwise we'd end up with the `Pressure Tent` (at least logically) also being a big logistics problem, which we probably neither should have nor want to have (well, one could make the case that everything beyond `VacSuit` should be a logistics effort, in which case my reasoning does not apply). Well, with the furniture and airlock (so the tent probably means it needs to depressurized every time anyone leaves or enters), I guess it should be `Large` in transport, but then still printable in parts?

I think `Size` should be specified as tripplets for critical items for which we care about logistics at all (which I think unless we do want high abstraction close to Bag of Holding would be usually -- if unclear [for example a hand gun probably does not need any thought to get to `Very Small` for all, while a `Sniper Rifle` might be `Small` in `Nanofabbing` and optionally transport, but `Medium` when usable/assembled, and the `Emergency Bubble` I consider to not be obvious at all, so should be defined when chosen])
- for `Nanofabbing`
- for transport
- in use/deployed

**Comment by irmejnah** [comment]
If we don't do anything like that I think there needs to be a common understanding that `Nanofabbing` in pieces is possible for most items, just meaning the result might need some skilled assembly and take some time. For the above, otherwise `Emergency Bubble` would not be possible to make even with a `Large Fabber`, which seems to border on ridiculous to me.

**Comment by itteerde** [comment]
Has not been a real problem yet, reopen if necessary, but not something worth doing anything about now.
